### ISSUE TITLE
Could't load library with v8 runtime ?

### ISSUE THREAD

**Issue by sylvainp** [mudderman/ViewPager-Module-Demo#2]
Hello,

I would like to use your library for my Titanium project but I'm not be able to use it. I import lib into my project and when i launch my app, I've got this error : 

<code>
java.lang.UnsatisfiedLinkError: Couldn't load net.bajawa.pager: findLibrary returned null
E/TiApplication( 1787):         at java.lang.Runtime.loadLibrary(Runtime.java:365)
E/TiApplication( 1787):         at java.lang.System.loadLibrary(System.java:535)
E/TiApplication( 1787):         at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:105)
E/TiApplication( 1787):         at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:72)
E/TiApplication( 1787):         at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:175)
E/TiApplication( 1787):         at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
E/AndroidRuntime( 1787): FATAL EXCEPTION: KrollRuntimeThread
E/AndroidRuntime( 1787): java.lang.UnsatisfiedLinkError: Couldn't load net.bajawa.pager: findLibrary returned null
E/AndroidRuntime( 1787):        at java.lang.Runtime.loadLibrary(Runtime.java:365)
E/AndroidRuntime( 1787):        at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime( 1787):        at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:105)
E/AndroidRuntime( 1787):        at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:72)
E/AndroidRuntime( 1787):        at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:175)
E/AndroidRuntime( 1787):        at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
</code>

I don't understand why I've got it. I'm using 3.0.0 GA Titanium SDK and V8 android runtime.

thank's in advance

**Comment by sylvainp** [comment]
The problem is caused by android emulator 

https://jira.appcelerator.org/browse/TIMOB-9170

there is an incompatibility between v8 runtime and x86 emulator

thank's for your lib, it works fine.
