### ISSUE TITLE
Crash on Android 4.0.3 and 4.0.4

### ISSUE THREAD

**Issue by timanrebel** [mudderman/ViewPager-Module-Demo#5]
Hi Thomas,

I see a lot of crashes on Android 4.0.3 and 4.0.4. Unfortunately I do not have a device with that specific Android version at hand, so can not test it (But will try to). The crashlog on Google Play says the following:

```
java.lang.NoSuchMethodError: android.widget.TextView.setBackground
at so.hau.tomas.pager.util.UIUtils.styleTabView(UIUtils.java:54)
at so.hau.tomas.pager.indicator.TabStyleFixed$TabView.updateStyle(TabStyleFixed.java:172)
at so.hau.tomas.pager.indicator.TabStyleFixed$TabView.<init>(TabStyleFixed.java:157)
at so.hau.tomas.pager.indicator.TabStyleFixed.addTab(TabStyleFixed.java:56)
at so.hau.tomas.pager.indicator.TabStyleFixed.notifyDataSetChanged(TabStyleFixed.java:70)
at so.hau.tomas.pager.indicator.TabStyleFixed.setViewPager(TabStyleFixed.java:130)
at so.hau.tomas.pager.view.BaseView.setTabsIndicator(BaseView.java:68)
at so.hau.tomas.pager.view.ViewPager.processProperties(ViewPager.java:119)
at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1185)
at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:480)
at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:471)
at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:449)
at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:487)
at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:471)
at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:449)
at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:566)
at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:544)
at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:303)
at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:32)
at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:452)
at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:528)
at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
at android.app.Activity.performCreate(Activity.java:4492)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
at android.app.ActivityThread.access$600(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
```

Is this something that looks familiair to you?

**Comment by mudderman** [comment]
Yes, when I did the re-write I accidentally used a method (setBackground) in TextView (or rather View) that was added in 4.1 (api level 16). This has been fixed and I have a newer version laying around (just have to find it) I will then post the link to it. Sorry for the inconvenience.

**Comment by timanrebel** [comment]
No problem! Were just 1300 crashes in 6 days ;-)

No really, no problem. It is open source software and would really appreciate the update. Let me know if I can help you in anyway. (A donation for example?)

**Comment by kbshl** [comment]
Hi,

thnx for this great module, I love it! Can I also have the version with the setBackground-Fix? :)

**Comment by shopmium** [comment]
Hi Thomas, 

Thanks for your module, can you fix it as soon as possible or is it possible to publish your source code for contributions ?
